### ISSUE TITLE
Deadline für Funktionen Skript

### ISSUE THREAD

**Issue by Extern7** [Extern7/GitHub-Aufgabe-Gruppe2-Wissenschaftliches-Arbeiten#2]
Wir sollten eine Deadline für das Fertigstellen der Funktionen Skripts festlegen. Ihr braucht ja auch noch Zeit um die fertigen Funktionen bei der Analyse anzuwenden und danach müssen wir noch darüber diskutieren.

Es ist euch überlassen wie viel Zeit ihr für die Analyse braucht, aber mein erster Gedanke wäre, dass die Funktionen Skripts morgen früh fertig sein sollten.  Dann bleiben noch anderthalb Tage für das Anwenden und Diskutieren.

**Comment by Me37127** [comment]
Ich habe gerade nachgeschaut. Das Funktionen-Skript 1 müsste soweit fertig sein. Stefan hat es gestern Abend/ Nachts noch aktualisiert. Wir benötigen noch ein Funktionen-Skript 2 für interne Funktionen. Das werde ich schon mal anlegen und dann können Stefan und ich auch richtig mit der Analyse beginnen.
