### ISSUE TITLE
Falscher Datensatz bei Update #1

### ISSUE THREAD

**Issue by merfi8** [Extern7/GitHub-Aufgabe-Gruppe2-Wissenschaftliches-Arbeiten#6]
Der Datensatz ohne rownames ist nicht der richtige.

**Comment by Extern7** [comment]
Wenn wir einen neuen Datensatz ohne rownames erstellen, wie gefordert gewesen ist, wird natürlich auch die Simulation neu durchgeführt. Der Datensatz ohne rownames, den wir vor 2 Tagen hochgeladen haben ist also "der Richtige". Wenn ihr schon mit dem anderen gearbeitet habt könnt ihr den auch aus der History bekommen. Ich gucke aber auch mal ob ich den nochmal extra hochladen kann.

**Comment by merfi8** [comment]
Die Verteilung ist aber ganz anders. Ich komme nicht zu den gleichen Ergebnissen wie Melvin.

**Comment by Extern7** [comment]
Das liegt einfach daran, dass eine Simulation für 100 Leute nicht so toll signifikante Aussagen bringt. Das meiste davon ist Zufall und bei 2 Simulationen werden die Ergebnisse anders aussehen. Damit es aber nicht verwirrend ist, solltet ihr euch vielleicht einfach auf den "alten" Datensatz fokussieren. Ich versuche den nocheinmal hochzuladen.

**Comment by Extern7** [comment]
Achtet nur darauf bei der Analyse deutlich zu machen, welchen Datensatz ihr benutzt.
