### ISSUE TITLE
Bei der Analyse beachten: read.csv in das Analyse-Skript hinzufügen

### ISSUE THREAD

**Issue by Pata95** [Extern7/GitHub-Aufgabe-Gruppe2-Wissenschaftliches-Arbeiten#8]
Die R Skripts sollen komplett durchlaufen können also müsst ihr im analyse skript am  Anfang
data <- read.csv("original_datensatz_ohne_rownames.csv") oder data <- read.csv("datensatz.csv") 
definieren. Hauptsache es ist zu erkennen was "data" ist :) .

**Comment by Me37127** [comment]
Genau. Hatten wir gemacht, jedoch nicht hochgeladen.  Werde es eben ergänzen
